# Assignment 02:  Python basics

The purpose of this assignment is learn the fundamentals of Python programming, including:

1. Basic math
1. Variables
1. Lists, tuples and arrays
1. Packages: `math` and `numpy`
1. Functions


___

### Example problem

Q. Use Python to calculate and print the result of:

<br>

<center>$\begin{eqnarray*}
    4 \times 5
\end{eqnarray*}$</center>

### Answer to example problem:

In [1]:
print( 4 * 5 )

20


___

# (1)  Basic math

Q. Use Python to calculate and print the result of:

<br>

<center>$\begin{eqnarray*}
    (3 + 1) \times 2
\end{eqnarray*}$</center>

In [ ]:
print((3 + 1) * 2)

8


Q. Use Python to calculate and print the result of:

<br>

<center>$\begin{eqnarray*}
    (4 + 6) ^ 2
\end{eqnarray*}$</center>

In [1]:
print((4 + 6)**2)

100


Q. Use Python to calculate and print the result of:

<br>

<center>$\begin{eqnarray*}
    \frac{ (3 + 1) \times 2 }{ (4 + 6) ^ 2 }
\end{eqnarray*}$</center>

In [2]:
print(((3 + 1) * 2)/((4 + 6)**2))

0.08


___

# (2)  Variables

Q. Use Python to calculate then print the value of `y`.

<br>

<center>$\begin{eqnarray*}
    x &=& 5 \\
    y &=& (x^2 + 1)
\end{eqnarray*}$</center>

In [3]:
x = 5
y = (x**2 + 1)
print(y)

26


Q. Use Python to calculate then print the value of `y`.

<br>

<center>$\begin{eqnarray*}
    a &=& 5 \\
    b &=& 10 \\
    c &=& 20 \\
    x &=& -1 \\
    y &=& (ax^2 + bx + c)
\end{eqnarray*}$</center>

In [4]:
a = 5
b = 10
c = 20
x = -1
y = (a*x**2 + b*x + c)
print(y)

15


Q. Use Python to calculate then print the value of `y`.

<br>

<center>$\begin{eqnarray*}
    x_0 &=& 50 \\
    x_1 &=& 3 x_0 - 50\\
    y &=& \left(\frac{x_0}{x_1}\right)^2
\end{eqnarray*}$</center>

In [7]:
x0 = 50
x1 = 3*x0 - 50
y = (x0/x1)
print(y)

0.5


___

# (3) Lists and tuples

Q. Use Python to construct `x` as a **list**, then print its **second** value.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}10 & 8 & 20 & 6 & 30\end{bmatrix}
\end{eqnarray*}$</center>

In [8]:
x = [10, 8, 20, 6, 30]
print(x[1])

8


Q. Use Python to construct `x` as a **tuple**, then print its **last** value.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{pmatrix}5 & 2 & 1\end{pmatrix}
\end{eqnarray*}$</center>

In [10]:
x = (5, 2, 1)
print(x[-1])

1


Q. Use Python to construct `x` as a **list** of **tuples**, then print the **last** tuple.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}\begin{pmatrix}5 & 2 & 1\end{pmatrix}, \begin{pmatrix}1 & 3 & 3\end{pmatrix}, \begin{pmatrix}0 & -1 & -2\end{pmatrix}\end{bmatrix}
\end{eqnarray*}$</center>

In [11]:
x = [(5, 2, 1), (1, 3, 3), (0, -1, -2)]
print(x[-1])

(0, -1, -2)


Q. Use Python to create an empty list `x`, then use three `append` commands to create and print the following list. 

**NOTE!**: your Python code should have **five** commands including three `append` commands and one `print` command.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}5 & \begin{pmatrix}1 & 2\end{pmatrix}  & \begin{bmatrix}4 & 5 & 6\end{bmatrix}\end{bmatrix}
\end{eqnarray*}$</center>

In [13]:
x = []
x.append(5)
x.append((1, 2))
x.append([4, 5, 6])
print(x)

[5, (1, 2), [4, 5, 6]]


___

# (4) Packages: math and numpy

### `math`

Q. Use the `math` package to calculate `x`. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& \sin(\pi/2) - \cos(\pi) 
\end{eqnarray*}$</center>

In [15]:
import math 

x = math.sin(math.pi/2) - math.cos(math.pi)
print(x)

2.0


Q. Use the `math` package to calculate `y`. Print the result.

<br>

<center>$\begin{eqnarray*}
    x_0 &=& 3\\
    x_1 &=& 4\\
    y &=& \sqrt{x_0^2 + x_1^2}
\end{eqnarray*}$</center>

In [16]:
x0 = 3
x1 = 4
y = math.sqrt(x0**2 + x1**2)
print(y)

5.0


Q. Use the `math` package to calculate `x`. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& e ^ {\log(10) }
\end{eqnarray*}$</center>

In [27]:
x = math.e**math.log(10)
print(x)

10.000000000000002


### `numpy`

Q.  Use the `numpy` package to construct the following 1D array. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}5 & 2 & 1\end{bmatrix}
\end{eqnarray*}$</center>

In [22]:
import numpy as np

x = np.array([5, 2, 1])
print(x)

[5 2 1]


Q.  Use the `numpy` package to construct the following 2D array. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}5 & 2 & 1\\ 1 & 3 & 3\\ 0 & -1 & -2\end{bmatrix}
\end{eqnarray*}$</center>

In [25]:
x = np.array([[5, 2, 1], [1, 3, 3], [0, -1, -2]])
print(x)

[[ 5  2  1]
 [ 1  3  3]
 [ 0 -1 -2]]


Q. Use the `numpy` package to compute `x`. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}5\\2\\1\end{bmatrix} + 1
\end{eqnarray*}$</center>

In [29]:
x = np.array([5, 2, 1]) + 1 
print(x)


[6 3 2]


Q. Use the `numpy` package to compute `x`. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}5\\2\\1\end{bmatrix} + \begin{bmatrix}3\\-4\\8\end{bmatrix}
\end{eqnarray*}$</center>

In [30]:
x = np.array([5, 2, 1]) + np.array([3, -4, 8])
print(x)

[ 8 -2  9]


___

# (5) Functions

Q. Create a function called `myfunction` that calculates $f(x)$. Use this function to calculate $f(x)$ for $x=5$. Print the result.

<br>

<center>$\begin{eqnarray*}
    f(x) &=& 2(x - 1) + 5
\end{eqnarray*}$</center>

In [41]:
def myfunction(x): 
    return 2*(x - 1) + 5

x = 5

print(myfunction(x))

13


Q. Create a function called `two_argument_function` that calculates $f(a, b)$. Use this function to calculate $f(a, b)$ for $a=3$ and $b=2$. Print the result.

<br>

<center>$\begin{eqnarray*}
    f(a, b) &=& b^a + 1
\end{eqnarray*}$</center>

In [38]:
def two_argument_function(a, b):
    return b**a + 1

a = 3
b = 2

print(two_argument_function(a, b))

9


Q. Create a function called `add_vectors` that calculates $f(\boldsymbol{x}_0, \boldsymbol{x}_1)$. Use this function to calculate $f(\boldsymbol{x}_0, \boldsymbol{x}_1)$ for $\boldsymbol{x}_0=\begin{bmatrix}5\\2\\1\end{bmatrix}$ and $\boldsymbol{x}_1=\begin{bmatrix}1\\2\\10\end{bmatrix}$. Print the result.

<br>

<center>$\begin{eqnarray*}
    f(\boldsymbol{x}_0, \boldsymbol{x}_1) &=&  \boldsymbol{x}_0 + \boldsymbol{x}_1
\end{eqnarray*}$</center>

In [39]:
def add_vectors(x0, x1):
    return x0 + x1

x0 = np.array([5, 2, 1])
x1 = np.array([1, 2, 10])

print(add_vectors(x0, x1))

[ 6  4 11]


Q. Create a Python function that represent the following mathematical function:

<br> 

<center>$\begin{eqnarray*}
    f(\boldsymbol{a}, b, c) &=& b\boldsymbol{a} + \begin{bmatrix}0\\c\\0\end{bmatrix}
\end{eqnarray*}$</center>

<br> 

Note that $\boldsymbol{a}$ is a vector, and that $b$ and $c$ are scalars.

<br>

Use the function you created to calculate $f(\boldsymbol{a},b,c)$ for: $\boldsymbol{a} = \begin{bmatrix}1\\0\\2\end{bmatrix}$, $b=5$ and $c$=10.

Print your solution.

<br> 



In [42]:
def f(a, b, c):
    return b*a + np.array([0, c, 0])

a = np.array([1, 0, 2])
b = 5
c = 10

print(f(a, b, c))

[ 5 10 10]
